# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcc2b133d58ed3318e6688065d7731a1158625181fe5e5a381984109cdfc210c7a02cfa1cf7b65119b8f782e0a47ab834b2aa67281aba84f6e4805500aba719

test:
  secret_key_base: d6187b19c66acee84b5ff92701f1450344e9eb48c1917082029438d16c9406a7483c7097bbd2a22b281e232a5ef92109a6a451a31b51dc87b97a0002a3288581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
